version: "2"
services:
  INVERTER_MQTT_Gateway:
    image: mradziwo/dss_inv_mqtt

    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /home/containers/inverter/config:/app/config

